### ISSUE TITLE
Webhook headers incorrect type

### ISSUE THREAD

**Issue by kellpossible** [bigcommerce/api-specs#1377]
https://github.com/bigcommerce/api-specs/blob/main/reference/webhooks.v3.yml#L3032

```yaml
        headers:
          type: object
          description: 'Headers used to validate that webhooks are active. You can pass in any number of custom headers to validate webhooks are being returned. '
          nullable: true
          properties:
            custom:
              type: string
```

Should probably be:
```yaml
        headers:
          type: object
          description: 'Headers used to validate that webhooks are active. You can pass in any number of custom headers to validate webhooks are being returned. '
          nullable: true
          additionalProperties:
             type: string
```
